version: '3'

services:
  # proxy:
  #   image: nginx:1.13.3
  #   links:
  #     - api:api
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:80

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
      - /code/node_modules
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    expose:
      - 27017
    # volumes:
    #   - mongodata:/data/db

# volumes:
#   mongodata: