# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  # proxy:
  #   image: nginx:1.13.3
  #   links:
  #     - node-app:node-app
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:80

  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ./src:/code
      - /code/node_modules
    ports:
      - 8080:3000
