# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  proxy:
    image: nginx:1.13.3
    # links:
    #   - app:app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  app:
    build:
      context: .
      dockerfile: node.Dockerfile

  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     POSTGRES_USER: barebear
  #     POSTGRES_PASSWORD: simplepassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: always

volumes:
  postgres-data:
